services:
  db:
    image: postgres:16
    container_name: imagematch_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imagematch
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
