"""add unique constraint on approvals.suggestion_id

Revision ID: e04664edf159
Revises: fb8f967e0a27
Create Date: 2026-08-30 18:43:14.929391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e04664edf159'
down_revision: Union[str, Sequence[str], None] = 'fb8f967e0a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_approval_suggestion_id', 'approvals', ['suggestion_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_approval_suggestion_id', 'approvals', type_='unique')
    # ### end Alembic commands ###
